# Generated by Django 3.2.4 on 2021-06-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendervideo', to='video.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Рендер',
                'verbose_name_plural': 'Рендеры',
            },
        ),
    ]
