# Generated by Django 3.2.4 on 2021-06-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendervideo',
            name='new_video',
            field=models.FileField(blank=True, upload_to='', verbose_name='Видео после рендеринга'),
        ),
    ]
