# Generated by Django 3.2.4 on 2021-06-17 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('api', '0002_rendervideo_new_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendervideo',
            name='new_video',
        ),
        migrations.AlterField(
            model_name='rendervideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendervideo', to='video.video', verbose_name='Видео первоначальное'),
        ),
    ]
