# Generated by Django 3.2.4 on 2021-06-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('video', models.FileField(upload_to='uploads/videos/%Y/%m/%d/', verbose_name='Видео')),
                ('background', models.ImageField(blank=True, upload_to='uploads/images/%Y/%m/%d/', verbose_name='Фоновое фото')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
